# Generated by Django 5.1.1 on 2024-11-03 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.CharField(db_column='admin_id', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('admin_username', models.CharField(db_column='admin_username', max_length=150, unique=True)),
                ('admin_pwd', models.CharField(db_column='admin_pwd', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('admin_email', models.EmailField(db_column='admin_email', max_length=255, unique=True)),
                ('admin_tel', models.CharField(db_column='admin_tel', max_length=10)),
                ('admin_name', models.CharField(db_column='admin_fname', max_length=50)),
                ('admin_role', models.CharField(db_column='admin_role', max_length=10)),
                ('admin_lname', models.CharField(db_column='admin_lname', max_length=50)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.CharField(db_column='user_id', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='user_username', max_length=150, unique=True)),
                ('password', models.CharField(db_column='user_pwd', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('email', models.EmailField(db_column='user_email', max_length=255, unique=True)),
                ('tel', models.CharField(db_column='user_tel', max_length=10)),
                ('user_fname', models.CharField(db_column='user_fname', max_length=50)),
                ('user_role', models.CharField(db_column='user_role', max_length=10)),
                ('user_lname', models.CharField(db_column='user_lname', max_length=50)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_map',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(db_column='user_username', max_length=150, unique=True)),
                ('email', models.EmailField(db_column='user_email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='user_pwd', max_length=255)),
                ('tel', models.CharField(db_column='user_tel', max_length=10)),
                ('user_role', models.CharField(db_column='user_role', max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProposedFile',
            fields=[
                ('upload_id', models.CharField(db_column='upload_id', max_length=25, primary_key=True, serialize=False)),
                ('file_name', models.CharField(db_column='file_name', max_length=50)),
                ('file_type', models.CharField(db_column='file_type', max_length=5)),
                ('file_size', models.FloatField(db_column='file_size')),
                ('file_data', models.TextField(db_column='file_data')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True, db_column='uploaded_date')),
                ('file_path', models.TextField(db_column='file_path')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'proposed_file',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProposedText',
            fields=[
                ('text_id', models.CharField(db_column='text_id', max_length=25, primary_key=True, serialize=False, unique=True)),
                ('proposed_text', models.TextField(db_column='word_text', max_length=255)),
                ('word_class', models.SmallIntegerField(db_column='word_class', default=0)),
                ('word_status', models.CharField(blank=True, db_column='word_status', default='รออนุมัติ', max_length=30, null=True)),
                ('word_class_type', models.CharField(blank=True, db_column='word_class_type', max_length=100, null=True)),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admins')),
                ('upload_id', models.ForeignKey(db_column='uploaded_id', on_delete=django.db.models.deletion.CASCADE, to='users.proposedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'db_table': 'proposed_text',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proposedfile',
            name='text_id',
            field=models.ForeignKey(db_column='proposed_text_id', on_delete=django.db.models.deletion.CASCADE, to='users.proposedtext'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.CharField(db_column='task_id', max_length=6, primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(db_column='task_name', max_length=50)),
                ('created_date', models.DateField(db_column='created_date')),
                ('due_date', models.DateField(db_column='due_date')),
                ('kappa_score', models.FloatField(db_column='kappa_score')),
                ('task_status', models.SmallIntegerField(db_column='task_status')),
                ('admin', models.ForeignKey(blank=True, db_column='admin_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.admins')),
            ],
            options={
                'db_table': 'task',
            },
        ),
        migrations.CreateModel(
            name='AnnotatedText',
            fields=[
                ('annotated_id', models.BigIntegerField(db_column='annotated_id', primary_key=True, serialize=False, unique=True)),
                ('annotated_class', models.SmallIntegerField(db_column='annotated_class')),
                ('annotated_type', models.CharField(blank=True, db_column='annotated_type', default='1', max_length=30, null=True)),
                ('annotated_text', models.TextField(db_column='annotated_text')),
                ('annotated_date', models.DateTimeField(auto_now_add=True, db_column='annotated_date')),
                ('text_id', models.ForeignKey(blank=True, db_column='text_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.proposedtext')),
                ('task_id', models.ForeignKey(blank=True, db_column='task_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.task')),
            ],
            options={
                'db_table': 'annotated_text',
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('user_task_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateField()),
                ('latest_assign_date', models.DateField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'User Task',
                'verbose_name_plural': 'User Tasks',
                'db_table': 'user_task',
            },
        ),
    ]
