# Generated by Django 5.1.1 on 2024-10-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_proposedfile_proposed_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('admin_id', models.CharField(db_column='admin_id', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('admin_username', models.CharField(db_column='admin_username', max_length=150, unique=True)),
                ('admin_pwd', models.CharField(db_column='admin_pwd', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('admin_email', models.EmailField(db_column='admin_email', max_length=255, unique=True)),
                ('admin_tel', models.CharField(db_column='admin_tel', max_length=10)),
                ('admin_fname', models.CharField(db_column='admin_fname', max_length=50)),
                ('admin_lname', models.CharField(db_column='admin_lname', max_length=50)),
                ('admin_role', models.CharField(db_column='admin_role', max_length=10)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
